apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace:  roboshop
  labels:
    component: shipping
    project: roboshop
    tier: app
data:
  CART_ENDPOINT:  "cart:8080" 
  DB_HOST:  "mysql"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace:  roboshop
  labels:
    component: shipping
    project: roboshop
    tier: app
spec:
  replicas: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      component: shipping
      project: roboshop
      tier: app
  # this is pod definition
  template:
    metadata:
      labels:
        component: shipping
        project: roboshop
        tier: app
    spec:
      containers:
      - name: shipping
        image: maha110/shipping:v1 # this image is already buld in docker and pushed to docker hub. we are using it here to run container.
        envFrom:
        - configMapRef:
            name: shipping
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop # dont forget to mention this.
  #labels in service are used to filter service based on labels . 
  labels:
    component: shipping
    project: roboshop
    tier: app
spec:
  selector:
    component: shipping
    project: roboshop
    tier: app
  ports:
    - protocol: TCP
      port: 8080 # this is source(service) port
      targetPort: 8080 # container port
