apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  namespace:  roboshop
  labels:
    purpose: secret
    env: dev
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: "cm9ib3Nob3A="
  RABBITMQ_DEFAULT_PASS: "cm9ib3Nob3AxMjM="
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace:  roboshop
  labels:
    component: rabbitmq
    project: roboshop
    tier: database
spec:
  replicas: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      component: rabbitmq
      project: roboshop
      tier: database
  # this is pod definition
  template:
    metadata:
      labels:
        component: rabbitmq
        project: roboshop
        tier: database
    spec:
      containers:
      - name: rabbitmq
        image: maha110/rabbitmq:v1 
        envFrom:
          - secretRef:
              name: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  #labels in service are used to filter service based on labels . 
  labels:
    component: rabbitmq
    project: roboshop
    tier: database
spec:
  selector:
    component: rabbitmq
    project: roboshop
    tier: database
  ports:
    - protocol: TCP
      port: 5672 # this is source(service) port
      targetPort: 5672 # container port
