apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace:  roboshop
  labels:
    component: mongodb
    project: roboshop
    tier: database
spec:
  replicas: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      component: mongodb
      project: roboshop
      tier: database
  # this is pod definition
  template:
    metadata:
      labels:
        component: mongodb
        project: roboshop
        tier: database
    spec:
      containers:
      - name: mongodb
        image: maha110/mongodb:v1 # this image is already buld in docker and pushed to docker hub. we are using it here to run container.
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop # dont forget to mention this.
  #labels in service are used to filter service based on labels . 
  labels:
    component: mongodb
    project: roboshop
    tier: database
spec:
  selector:
    component: mongodb
    project: roboshop
    tier: database
  ports:
    - protocol: TCP
      port: 27017 # this is source(service) port
      targetPort: 27017 # container port
